### ISSUE TITLE
Default installation fails with MONGO_URI undefined 

### ISSUE THREAD

**Issue by shankarpnsn** [oslabs-beta/helmets#53]
Steps: 

1) cloned repo
2) npm install .
3) Run npm start

Step 3 fails when connecting to mongoDB. The env variable process.env.MONGO_URI is undefined. 

$ npm start

> helmets@1.0.0 start
> nodemon server/server.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/server.js`
listening on 3000
error connedting:  MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

**Comment by dev-cameron** [comment]
Hi @shankarpnsn

The mongoose service will initate the connection to MongoDB by reading MONGO_URI from your environment variables. Did you supply a URI connection string in your .env?

**Comment by SebastianLoes** [comment]
Got it to start (but sadly not work) using this docker compose
```
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
```
and export the connection string
```
export MONGO_URI=mongodb://root:example@localhost:27017
```
Would have been nice to see instructions for it in the documentation.
